/**
 * NAVI Agent Framework — Episodic Memory
 *
 * Stores summarized conversation episodes (not raw transcripts).
 * Each episode is a compressed summary of a conversation segment,
 * tagged with location, scenario, and importance.
 *
 * Design decision: Store summaries, not raw logs.
 * Raw conversation logs grow unbounded and contain mostly noise.
 * Episodic summaries are generated by the LLM after each conversation
 * and capture only what's worth remembering. This keeps storage tiny
 * and retrieval fast — critical for on-device.
 *
 * Persistence: IndexedDB via the existing storage layer.
 */

import type { EpisodicMemory } from '../core/types';
import { get, set } from 'idb-keyval';

const STORAGE_KEY = 'navi_episodic_memory';
const MAX_EPISODES = 100;
const IMPORTANCE_THRESHOLD = 0.3;

export class EpisodicMemoryStore {
  private episodes: EpisodicMemory[] = [];
  private loaded = false;

  /** Load episodes from IndexedDB */
  async load(): Promise<void> {
    const stored = await get<EpisodicMemory[]>(STORAGE_KEY);
    this.episodes = stored ?? [];
    this.loaded = true;
  }

  /** Persist episodes to IndexedDB */
  async save(): Promise<void> {
    await set(STORAGE_KEY, this.episodes);
  }

  /** Add a new episode and persist */
  async add(episode: Omit<EpisodicMemory, 'id'>): Promise<EpisodicMemory> {
    if (!this.loaded) await this.load();

    const entry: EpisodicMemory = {
      ...episode,
      id: `ep_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
    };

    this.episodes.push(entry);

    // Evict low-importance episodes if over capacity
    if (this.episodes.length > MAX_EPISODES) {
      this.episodes.sort((a, b) => b.importance - a.importance);
      this.episodes = this.episodes.slice(0, MAX_EPISODES);
    }

    await this.save();
    return entry;
  }

  /** Retrieve episodes by recency (most recent first) */
  getRecent(count: number = 10): EpisodicMemory[] {
    return [...this.episodes]
      .sort((a, b) => b.timestamp - a.timestamp)
      .slice(0, count);
  }

  /** Retrieve episodes relevant to a location */
  getByLocation(location: string, count: number = 5): EpisodicMemory[] {
    return this.episodes
      .filter((ep) => ep.location?.toLowerCase().includes(location.toLowerCase()))
      .sort((a, b) => b.importance - a.importance)
      .slice(0, count);
  }

  /** Retrieve episodes relevant to a scenario */
  getByScenario(scenario: string, count: number = 5): EpisodicMemory[] {
    return this.episodes
      .filter((ep) => ep.scenario === scenario)
      .sort((a, b) => b.importance - a.importance)
      .slice(0, count);
  }

  /** Retrieve episodes by tag */
  getByTag(tag: string, count: number = 5): EpisodicMemory[] {
    return this.episodes
      .filter((ep) => ep.tags.includes(tag))
      .sort((a, b) => b.importance - a.importance)
      .slice(0, count);
  }

  /** Search episodes by keyword in summary */
  search(query: string, count: number = 5): EpisodicMemory[] {
    const lower = query.toLowerCase();
    return this.episodes
      .filter((ep) => ep.summary.toLowerCase().includes(lower))
      .sort((a, b) => b.importance - a.importance)
      .slice(0, count);
  }

  /** Get episodes above importance threshold */
  getImportant(threshold: number = IMPORTANCE_THRESHOLD): EpisodicMemory[] {
    return this.episodes
      .filter((ep) => ep.importance >= threshold)
      .sort((a, b) => b.importance - a.importance);
  }

  /** Remove a specific episode */
  async remove(id: string): Promise<boolean> {
    const before = this.episodes.length;
    this.episodes = this.episodes.filter((ep) => ep.id !== id);
    if (this.episodes.length !== before) {
      await this.save();
      return true;
    }
    return false;
  }

  /** Clear all episodes */
  async clear(): Promise<void> {
    this.episodes = [];
    await this.save();
  }

  /** Get episodes from OTHER locations (for cross-location bridging) */
  getFromOtherLocations(currentLocation: string, tags?: string[], count: number = 5): EpisodicMemory[] {
    return this.episodes
      .filter((ep) => {
        if (!ep.location) return false;
        // Exclude current location
        if (ep.location.toLowerCase().includes(currentLocation.toLowerCase())) return false;
        // Optional tag filter
        if (tags && tags.length > 0) {
          return tags.some((tag) => ep.tags.includes(tag));
        }
        return true;
      })
      .sort((a, b) => b.importance - a.importance)
      .slice(0, count);
  }

  /** Get total count */
  get count(): number {
    return this.episodes.length;
  }

  /** Format episodes for injection into system prompt */
  formatForPrompt(episodes: EpisodicMemory[]): string {
    if (episodes.length === 0) return '';
    const lines = episodes.map(
      (ep) => `- [${new Date(ep.timestamp).toLocaleDateString()}] ${ep.summary}`,
    );
    return `Past interactions:\n${lines.join('\n')}`;
  }
}
