/**
 * NAVI Agent Framework — Semantic Memory (Vector Store)
 *
 * Stores embeddings for semantic retrieval. Supports top-K similarity
 * search using cosine similarity computed in pure JS (no external deps).
 *
 * Design decision: In-memory vector store with IndexedDB persistence.
 * For a phone with ~100-500 entries, brute-force cosine search is fast
 * enough (<5ms). No need for HNSW or Annoy indices at this scale.
 * If we ever hit 10K+ entries, swap to a WASM vector index.
 *
 * Embeddings are generated by the embedding model provider.
 * This store is model-agnostic — it just stores and searches vectors.
 */

import type { SemanticMemoryEntry } from '../core/types';
import { get, set } from 'idb-keyval';

const STORAGE_KEY = 'navi_semantic_memory';
const MAX_ENTRIES = 500;

export class SemanticMemoryStore {
  private entries: SemanticMemoryEntry[] = [];
  private loaded = false;

  async load(): Promise<void> {
    const stored = await get<SemanticMemoryEntry[]>(STORAGE_KEY);
    this.entries = stored ?? [];
    this.loaded = true;
  }

  async save(): Promise<void> {
    await set(STORAGE_KEY, this.entries);
  }

  /** Store a new entry with its embedding vector */
  async store(
    content: string,
    embedding: number[],
    metadata: Record<string, string> = {},
  ): Promise<SemanticMemoryEntry> {
    if (!this.loaded) await this.load();

    const entry: SemanticMemoryEntry = {
      id: `sem_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
      content,
      embedding,
      metadata,
      timestamp: Date.now(),
    };

    this.entries.push(entry);

    // Evict oldest if over capacity
    if (this.entries.length > MAX_ENTRIES) {
      this.entries = this.entries.slice(-MAX_ENTRIES);
    }

    await this.save();
    return entry;
  }

  /**
   * Find top-K similar entries by cosine similarity.
   * Returns entries sorted by similarity (highest first).
   */
  search(
    queryEmbedding: number[],
    topK: number = 5,
    metadataFilter?: Record<string, string>,
  ): Array<{ entry: SemanticMemoryEntry; similarity: number }> {
    let candidates = this.entries;

    // Apply metadata filter if provided
    if (metadataFilter) {
      candidates = candidates.filter((entry) =>
        Object.entries(metadataFilter).every(
          ([key, value]) => entry.metadata[key] === value,
        ),
      );
    }

    // Compute cosine similarities
    const scored = candidates.map((entry) => ({
      entry,
      similarity: cosineSimilarity(queryEmbedding, entry.embedding),
    }));

    // Sort by similarity descending and return top-K
    scored.sort((a, b) => b.similarity - a.similarity);
    return scored.slice(0, topK);
  }

  /** Remove an entry by id */
  async remove(id: string): Promise<boolean> {
    const before = this.entries.length;
    this.entries = this.entries.filter((e) => e.id !== id);
    if (this.entries.length !== before) {
      await this.save();
      return true;
    }
    return false;
  }

  /** Clear all entries */
  async clear(): Promise<void> {
    this.entries = [];
    await this.save();
  }

  get count(): number {
    return this.entries.length;
  }
}

/** Cosine similarity between two vectors. Returns 0-1. */
function cosineSimilarity(a: number[], b: number[]): number {
  if (a.length !== b.length || a.length === 0) return 0;

  let dotProduct = 0;
  let normA = 0;
  let normB = 0;

  for (let i = 0; i < a.length; i++) {
    dotProduct += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }

  const denominator = Math.sqrt(normA) * Math.sqrt(normB);
  if (denominator === 0) return 0;

  return dotProduct / denominator;
}
